### ISSUE TITLE
アイテムコントローラーの記述

### ISSUE THREAD

**Issue by chum2987** [chum2987/freemarket_sample_68a#42]
items_controller.rbの１０行目の記述を削除する。

[![Screenshot from Gyazo](https://gyazo.com/11c2395a3425e5f6ab59e97c8d320282/raw)](https://gyazo.com/11c2395a3425e5f6ab59e97c8d320282)

**Comment by takahiro-kgm** [comment]
このプルリクエストで修正しました◎
https://github.com/chum2987/freemarket_sample_68a/pull/43

**Comment by chum2987** [comment]
ありがとうございます！
